name: 'Conventional pull request (commitlint)'
description: 'lint commit title to conform to conventional standards'
author: 'Layton Whiteley'

branding:
  icon: 'heart'
  color: 'green'

inputs:
  config_file:
    description: 'Path to a commitlint config file in the repository'
    required: false
    default: ''

outputs:
  valid:
    description: 'Boolean as string with response if the process was valid or not'
  outcomes:
    description: 'JSON array as string for the detailed outcomes of the validation '
  report:
    description: 'Formatted string of the report'
  pr_title:
    description: 'The title of the pull request operated on'
  pr_number:
    description: 'The pull request number'

runs:
  using: node20
  main: dist/index.js
