env:
  node: true
  es6: true
  jest: true

globals:
  Atomics: readonly
  SharedArrayBuffer: readonly

ignorePatterns:
  - '!.*'
  - '**/node_modules/.*'
  - '**/dist/.*'
  - '**/coverage/.*'
  - '*.json'

# parser: '@stylistic/parser'

parserOptions:
  ecmaVersion: 2023
  sourceType: module
  project:
    - './.github/linters/tsconfig.json'
    - './tsconfig.json'

plugins:
  - jest
  - '@stylistic'

extends:
  # - eslint:recommended
  # - plugin:@stylistic/eslint-recommended
  # - plugin:@stylistic/recommended
  - plugin:github/recommended
  - plugin:jest/recommended

rules:
  {
    'camelcase': 'off',
    'eslint-comments/no-use': 'off',
    'eslint-comments/no-unused-disable': 'off',
    'i18n-text/no-en': 'off',
    'import/no-namespace': 'off',
    'no-console': 'off',
    'no-unused-vars': 'off',
    'prettier/prettier': 'error',
    '@stylistic/semi': 'warn',
    '@stylistic/array-type': 'error',
    '@stylistic/await-thenable': 'error',
    '@stylistic/ban-ts-comment': 'error',
    '@stylistic/consistent-type-assertions': 'error',
    '@stylistic/explicit-member-accessibility':
      ['error', { 'accessibility': 'no-public' }],
    '@stylistic/explicit-function-return-type':
      ['error', { 'allowExpressions': true }],
    '@stylistic/func-call-spacing': ['error', 'never'],
    '@stylistic/no-array-constructor': 'error',
    '@stylistic/no-empty-interface': 'error',
    '@stylistic/no-explicit-any': 'error',
    '@stylistic/no-extraneous-class': 'error',
    '@stylistic/no-for-in-array': 'error',
    '@stylistic/no-inferrable-types': 'error',
    '@stylistic/no-misused-new': 'error',
    '@stylistic/no-namespace': 'error',
    '@stylistic/no-non-null-assertion': 'warn',
    '@stylistic/no-require-imports': 'error',
    '@stylistic/no-unnecessary-qualifier': 'error',
    '@stylistic/no-unnecessary-type-assertion': 'error',
    '@stylistic/no-unused-vars': 'error',
    '@stylistic/no-useless-constructor': 'error',
    '@stylistic/no-var-requires': 'error',
    '@stylistic/prefer-for-of': 'warn',
    '@stylistic/prefer-function-type': 'warn',
    '@stylistic/prefer-includes': 'error',
    '@stylistic/prefer-string-starts-ends-with': 'error',
    '@stylistic/promise-function-async': 'error',
    '@stylistic/require-array-sort-compare': 'error',
    '@stylistic/restrict-plus-operands': 'error',
    '@stylistic/space-before-function-paren': 'off',
    '@stylistic/type-annotation-spacing': 'error',
    '@stylistic/unbound-method': 'error'
  }
